name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run dist

      - name: Upload Windows build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Inventory-Management-System-Windows
          path: release/*.exe

      - name: Upload Mac build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Inventory-Management-System-Mac
          path: release/*.dmg

      - name: Upload Linux build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Inventory-Management-System-Linux
          path: release/*.AppImage
